#version: '3.3'
#services:
#  mssql:
#    container_name: gamenight-mssql
#    image: mcr.microsoft.com/mssql/server:latest
#    restart: unless-stopped
#    environment:
#      ACCEPT_EULA: "Y"
#    env_file:
#      - .env.properties
#    ports:
#      - 1433:1433
#    volumes:
#      - ./db:/var/opt/mssql

services:
  database:
    container_name: gamenight-mysql
    image: mysql
    restart: unless-stopped
    ports:
     - 3306:3306
    env_file:
      - .env.properties # https://hub.docker.com/_/mysql - documentation for env file
    volumes:
      - ./docker/db:/var/lib/mysql