version: '3.3'
services:
  mssql:
    container_name: gamenight-mssql
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    env_file:
      - .env
    ports:
      - 1433:1433
    volumes:
      - ./db:/var/opt/mssql